name: "vertigo_case_dbt"
version: "1.0.0"
config-version: 2

profile: "vertigo_case_dbt"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  vertigo_case_dbt:
    +materialized: view
